baseurl = "/"
languageCode = "en-us"
theme = "anatole"
paginate = 5
summaryLength = 30
enableEmoji=true

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  mainSections = []
  # "light" or "dark"
  defaultTheme = "light"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3
  # Enable to show reading time in minutes for posts
  showReadingTime = false

  title = "I'm Dixi Yao"
  author = "Dixi Yao"
  description = "University of Toronto, EV.com, Hemlig AI"
  profilePicture = "assests/images/self.png"

  contentratio = 0.8

  copyright = "2023-{{ YEAR }}"
  readMore = true

  gtagId = "G-353217296"

[params.math]
enable = true 
use = "katex"

[languages]
  [languages.en.params]
    title = "Dixi Yao"
    subtitle = "Dixi Yao's Personal Website"
    keywords = ""

    [menu]
      [[menu.main]]
        identifier = "publications"
        weight = 2
        name = "Publications"
        url = "/publications"
      [[menu.main]]
        identifier = "project"
        weight = 3
        name = "Projects"
        url = "/projects"
      [[menu.main]]
        identifier = "blog_posts"
        weight = 4
        name = "Blog Posts"
        url = "/blog_posts"
      [[menu.main]]
        identifier = "gallery"
        weight = 5
        name = "Gallery"
        url = "/gallery"


[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:dixi@cs.uchicago.edu"
[[params.socialIcons]]
icon = "fa-brands fa-google-scholar"
title = "scholar"
url = "https://scholar.google.hk/citations?user=6f5HCVAAAAAJ&hl=en&oi=ao"
[[params.socialIcons]]
icon = "fa-brands fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/dixi-yao-328710261/"
[[params.socialIcons]]
icon ="fa-brands fa-github"
title = "Github"
url = "https://github.com/dixiyao"